### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by BeLimitless** [OpenXbox/xbox-webapi-python#1]
When trying to authenticate I receive the error below. Installed via PIP.

`Traceback (most recent call last):
  File "/usr/local/bin/xbox_authenticate", line 7, in <module>
    from xbox.webapi.scripts.authenticate import main
  File "/usr/local/lib/python2.7/dist-packages/xbox/webapi/scripts/authenticate.py", line 6, in <module>
    from xbox.webapi.authentication.manager import AuthenticationManager
  File "/usr/local/lib/python2.7/dist-packages/xbox/webapi/authentication/manager.py", line 24, in <module>
    from xbox.webapi.authentication.two_factor import TwoFactorAuthentication
  File "/usr/local/lib/python2.7/dist-packages/xbox/webapi/authentication/two_factor.py", line 8, in <module>
    from xbox.webapi.common.enum import Enum
  File "/usr/local/lib/python2.7/dist-packages/xbox/webapi/common/enum.py", line 23
    class Enum(metaclass=EnumType):
                        ^
SyntaxError: invalid syntax`

**Comment by BeLimitless** [comment]
Update: Never mind, I see it is executing from version 2.7 instead of 3.

**Comment by tuxuser** [comment]
Hi,
Indeed, python >= 3.4 is required.
Does authentication work for you now?

**Comment by BeLimitless** [comment]
Upgrading the workspace as we speak, will let you know.

**Comment by BeLimitless** [comment]
Yes, it is working, thanks for the fast reply.
