### ISSUE TITLE
TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object

### ISSUE THREAD

**Issue by carlberg74** [OpenXbox/xbox-webapi-python#14]
Hi,
Why do I always get error such as this;

user@ubuntu1604:~$ xbox-poweroff --all
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.AccessToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.RefreshToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.UserToken'> from file
INFO:authentication:Loaded token <class 'xbox.webapi.authentication.token.XSTSToken'> from file
Traceback (most recent call last):
  File "/usr/local/bin/xbox-poweroff", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/scripts/poweroff.py", line 63, in main
    state = c.connect(userhash, token)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/console.py", line 284, in connect
    xsts_token=xsts_token)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/protocol.py", line 452, in connect
    self.send_message(m)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/protocol.py", line 137, in send_message
    data = packer.pack(msg, self.crypto)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/packer.py", line 117, in pack
    packed_protected = crypto.encrypt(iv, packed_protected)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/crypto.py", line 274, in encrypt
    return Crypto._encrypt(self._encrypt_key, iv, plaintext)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/crypto.py", line 323, in _encrypt
    return Crypto._crypt(key=key, iv=iv, encrypt=True, data=data)
  File "/usr/local/lib/python3.5/dist-packages/xbox/sg/crypto.py", line 341, in _crypt
    return cryptor.update(data) + cryptor.finalize()
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/usr/local/lib/python3.5/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
**TypeError: from_buffer() cannot return the address of the raw string within a bytes or unicode or bytearray object**

I am able to authenticate and discover, but when I try something else I always get that error.
I have check dependencies and versions, and it all seem correct.
What am I missing.

Running Version: 1.1.7

**Comment by carlberg74** [comment]
xbox-poweron with liveid seem to work, but no other commands..
xbox-poweroff --all or with liveid gives same error.
..all commands that tries to use connect on xbox-client fails due to crypto.py line 323.

**Comment by carlberg74** [comment]
No one else has this problem?
Running ubuntu 16.04..
