### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by EquusRaphanus** [OpenXbox/xbox-webapi-python#43]
Trying to authenticate following instructions in the readme fails, giving the following error:

```
Traceback (most recent call last):
  File "/home/USER/.local/bin/xbox-authenticate", line 8, in <module>
    sys.exit(main())
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/webapi/scripts/authenticate.py", line 96, in main
    loop.run_until_complete(
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/USER/.local/lib/python3.8/site-packages/xbox/webapi/scripts/authenticate.py", line 45, in async_main
    auth_mgr.oauth = OAuth2TokenResponse.parse_raw(tokens)
  File "pydantic/main.py", line 538, in pydantic.main.BaseModel.parse_raw
  File "pydantic/main.py", line 515, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 362, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 6 validation errors for OAuth2TokenResponse
token_type
  field required (type=value_error.missing)
expires_in
  field required (type=value_error.missing)
scope
  field required (type=value_error.missing)
access_token
  field required (type=value_error.missing)
refresh_token
  field required (type=value_error.missing)
user_id
  field required (type=value_error.missing)
```

It seems that this may be affecting xbox-tui and xbox-nano-client as well, because neither of those are working and both are complaining about authentication in their errors.

**Comment by bsled96** [comment]
Did you ever figure this out?
