### ISSUE TITLE
Error attempting to bind on address while authenticating. 

### ISSUE THREAD

**Issue by uxm5jc** [OpenXbox/xbox-webapi-python#52]
While going through the authentication step in the README I had input this command as per the instructions: **xbox-authenticate -client-id (insert ID) --client-secret (Insert ID)** and recieved the following from the console. Running CentOS7

Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1062, in create_server
    sock.bind(sa)
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/xbox-authenticate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/xbox/webapi/scripts/authenticate.py", line 95, in main
    loop.run_until_complete(site.start())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib64/python3.6/site-packages/aiohttp/web_runner.py", line 128, in start
    reuse_port=self._reuse_port,
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 1066, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 8080): address already in use

Please provide whatever support you can holy devs, and guide this poor idiot through whatever seems to be the problem here.

**Comment by tuxuser** [comment]
Closing your issues now because you did not even try to troubleshoot yourself.
