### ISSUE TITLE
Error 500 when runnin xbox-authenticate.

### ISSUE THREAD

**Issue by LpsHeitor** [OpenXbox/xbox-webapi-python#73]
I'm currently trying to use [xbox smartglass nano]([xbox-smartglass-nano](https://github.com/OpenXbox/xbox-smartglass-nano-python)) and have successfully installed the application. However, the next step would be running xbox-authenticate to create the needed token files.

The xbox-authentication command opens the browser where i can effectively insert account info and allow the conection to WebApi. Still, after this, there is a Error 500 screen.

How could I solve this?

**Comment by LpsHeitor** [comment]
More detailed error mensage 

`[16948:16948:0303/183352.161934:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[16904:17201:0303/183415.608469:ERROR:chrome_browser_main_extra_parts_metrics.cc(226)] crbug.com/1216328: Checking Bluetooth availability started. Please report if there is no report that this ends.
[16904:17201:0303/183415.608584:ERROR:chrome_browser_main_extra_parts_metrics.cc(229)] crbug.com/1216328: Checking Bluetooth availability ended.
[16904:17201:0303/183415.608650:ERROR:chrome_browser_main_extra_parts_metrics.cc(232)] crbug.com/1216328: Checking default browser status started. Please report if there is no report that this ends.
[16904:17201:0303/183415.657729:ERROR:chrome_browser_main_extra_parts_metrics.cc(236)] crbug.com/1216328: Checking default browser status ended.
Error handling request
Traceback (most recent call last):
  File "/home/heitor/.local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/home/heitor/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/heitor/.local/lib/python3.6/site-packages/xbox/webapi/scripts/authenticate.py", line 25, in auth_callback
    asyncio.create_task(queue.put(request.query["code"]))
AttributeError: module 'asyncio' has no attribute 'create_task'
[16948:16948:0303/183426.514242:ERROR:shared_image_manager.cc(214)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[16904:16935:0303/183447.207250:ERROR:connection_factory_impl.cc(425)] Failed to connect to MCS endpoint with error -106
[16904:16935:0303/185708.084144:ERROR:connection_factory_impl.cc(425)] Failed to connect to MCS endpoint with error -106
`

**Comment by tuxuser** [comment]
You have to update to python 3.7
